// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Master.API.Models;

public partial class Airline
{
    public int AirlineId { get; set; }

    public string AirlineName { get; set; }

    public string LogoUrl { get; set; }

    public virtual ICollection<Flight> Flights { get; set; } = new List<Flight>();
}