// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Master.API.Models;

public partial class Application
{
    public int ApplicationId { get; set; }

    public int? JobId { get; set; }

    public int? UserId { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Interview> Interviews { get; set; } = new List<Interview>();

    public virtual Job Job { get; set; }

    public virtual User User { get; set; }
}