// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Master.API.Models;

public partial class Company
{
    public int CompanyId { get; set; }

    public string CompanyName { get; set; }

    public string LogoUrl { get; set; }

    public virtual ICollection<Hr> Hrs { get; set; } = new List<Hr>();

    public virtual ICollection<Interviewer> Interviewers { get; set; } = new List<Interviewer>();

    public virtual ICollection<Job> Jobs { get; set; } = new List<Job>();
}