// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Master.API.Models;

public partial class Hr
{
    public int Hrid { get; set; }

    public int? UserId { get; set; }

    public int? CompanyId { get; set; }

    public string HrName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public virtual Company Company { get; set; }

    public virtual ICollection<Interviewer> Interviewers { get; set; } = new List<Interviewer>();

    public virtual User User { get; set; }
}