// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Master.API.Models;

public partial class Interview
{
    public int InterviewId { get; set; }

    public int? ApplicationId { get; set; }

    public int? InterviewerId { get; set; }

    public DateTime? Date { get; set; }

    public string Feedback { get; set; }

    public virtual Application Application { get; set; }

    public virtual Interviewer Interviewer { get; set; }
}