// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Master.API.Models;

public partial class Job
{
    public int JobId { get; set; }

    public int? CompanyId { get; set; }

    public string JobTitle { get; set; }

    public string JobDescription { get; set; }

    public virtual ICollection<Application> Applications { get; set; } = new List<Application>();

    public virtual Company Company { get; set; }
}